In [14]:
#Q1
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)


(2, 4)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
      print(x)


1
2
3


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6]),)


In [ ]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


In [ ]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)


[41 43]


In [ ]:
#Q2)
arr1 = np.arange(0,12).reshape([3,4])
print(arr1)
np.sum(arr1,axis =0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [15]:
#Q3)
import numpy as np
monthly_high_temperatures = np.array([25, 28, 30, 24, 23, 21, 32, 22, 28, 29, 31, 33])
monthly_low_temperatures = np.array([50, 45, 40, 38, 37, 41, 39, 36, 46, 40, 48, 55])
monthly_average_temperatures = (monthly_high_temperatures + monthly_low_temperatures) / 2
overall_average_high = np.mean(monthly_high_temperatures)
overall_average_low = np.mean(monthly_low_temperatures)
highest_avg_temp_month = np.argmax(monthly_average_temperatures) + 1
lowest_avg_temp_month = np.argmin(monthly_average_temperatures) + 1
print("Monthly High Temperatures:", monthly_high_temperatures)
print("Monthly Low Temperatures:", monthly_low_temperatures)
print("Monthly Average Temperatures:", monthly_average_temperatures)
print("Overall Average High Temperature:", overall_average_high)
print("Overall Average Low Temperature:", overall_average_low)
print("Month with the Highest Average Temperature:", highest_avg_temp_month)
print("Month with the Lowest Average Temperature:", lowest_avg_temp_month)





Monthly High Temperatures: [25 28 30 24 23 21 32 22 28 29 31 33]
Monthly Low Temperatures: [50 45 40 38 37 41 39 36 46 40 48 55]
Monthly Average Temperatures: [37.5 36.5 35.  31.  30.  31.  35.5 29.  37.  34.5 39.5 44. ]
Overall Average High Temperature: 27.166666666666668
Overall Average Low Temperature: 42.916666666666664
Month with the Highest Average Temperature: 12
Month with the Lowest Average Temperature: 8


In [ ]:
from numpy.random import default_rng
arr = int(default_rng().random(1)*100)
print(arr)


92


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a[1,1:4])

[7 8 9]
